version: '3'
services:
  2023ciscn-prj:
    container_name: 2023ciscn-prj
    build: .
    volumes:
      - ./:/app/
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576

